version: '3'
services:
    mglite_mysql:
        image: mysql
        ports: ["31579:3306"]
        environment:
            MYSQL_ROOT_PASSWORD: passwd
            MYSQL_DATABASE: testdb
        command:
          - mysqld
          - "--character-set-server=utf8mb4"
          - "--collation-server=utf8mb4_unicode_ci"
          - "--default-time-zone=+08:00"
          - "--sql-mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"